# Generated by Django 5.2.6 on 2025-09-18 13:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_cd', models.CharField(max_length=20, verbose_name='部署コード')),
                ('relation_group_cd', models.CharField(max_length=20, verbose_name='関連部署コード')),
            ],
            options={
                'verbose_name': '組織関係ビュー',
                'verbose_name_plural': '組織関係ビュー',
                'db_table': 'v_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='M_Account',
            fields=[
                ('account_cd', models.CharField(default='DEFAULT', max_length=20, primary_key=True, serialize=False, verbose_name='勘定科目コード')),
                ('account_name', models.CharField(max_length=100, verbose_name='勘定科目名')),
            ],
        ),
        migrations.CreateModel(
            name='M_Bumon',
            fields=[
                ('bumon_cd', models.CharField(default='DEFAULT', max_length=15, primary_key=True, serialize=False, verbose_name='部門コード')),
                ('bumon_name', models.CharField(max_length=100, verbose_name='部門名')),
            ],
        ),
        migrations.CreateModel(
            name='M_Group',
            fields=[
                ('group_cd', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='部署コード')),
                ('group_name', models.CharField(max_length=50, verbose_name='部署名')),
                ('upper_group_cd', models.CharField(blank=True, max_length=20, null=True, verbose_name='上位部署コード')),
            ],
            options={
                'verbose_name': '所属部署マスタ',
                'verbose_name_plural': '所属部署マスタ',
                'db_table': 'm_group',
            },
        ),
        migrations.CreateModel(
            name='M_Post',
            fields=[
                ('post_cd', models.CharField(default='DEFAULT', max_length=15, primary_key=True, serialize=False, verbose_name='役職コード')),
                ('post_name', models.CharField(max_length=100, verbose_name='役職名')),
            ],
        ),
        migrations.CreateModel(
            name='M_Status',
            fields=[
                ('status_cd', models.CharField(default='DEFAULT', max_length=20, primary_key=True, serialize=False, verbose_name='ステータスコード')),
                ('status_name', models.CharField(max_length=50, verbose_name='ステータス名')),
            ],
        ),
        migrations.CreateModel(
            name='M_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('man_number', models.CharField(max_length=20, unique=True, verbose_name='社員番号')),
                ('user_name', models.CharField(max_length=30, verbose_name='氏名')),
                ('role', models.CharField(choices=[('employee', '従業員'), ('approver', '承認者'), ('accountant', '経理担当者'), ('final_approver', '経理承認者')], default='employee', max_length=20, verbose_name='権限')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('bumon_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.m_bumon', verbose_name='部門')),
                ('post_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.m_post', verbose_name='役職')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='T_ExpenseMain',
            fields=[
                ('expense_main_id', models.AutoField(primary_key=True, serialize=False, verbose_name='申請ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='合計金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
                ('approver_man_number_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_approvals', to=settings.AUTH_USER_MODEL, verbose_name='承認者1')),
                ('approver_man_number_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_approvals', to=settings.AUTH_USER_MODEL, verbose_name='承認者2')),
                ('status_cd', models.ForeignKey(default='SUBMITTED', on_delete=django.db.models.deletion.PROTECT, to='expenses.m_status', verbose_name='ステータス')),
            ],
        ),
        migrations.CreateModel(
            name='T_ExpenseDetail',
            fields=[
                ('expense_detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='明細ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('purpose', models.CharField(max_length=255, verbose_name='目的')),
                ('receipt', models.FileField(blank=True, null=True, upload_to=expenses.models.receipt_upload_path, verbose_name='領収書')),
                ('receipt_thumbnail', models.ImageField(blank=True, null=True, upload_to=expenses.models.thumbnail_upload_path, verbose_name='サムネイル')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='取引先')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.m_account', verbose_name='勘定科目')),
                ('expense_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='expenses.t_expensemain', verbose_name='経費申請')),
            ],
        ),
        migrations.CreateModel(
            name='T_ApprovalLog',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False, verbose_name='承認ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='承認日時')),
                ('man_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('status_cd', models.ForeignKey(default='SUBMITTED', on_delete=django.db.models.deletion.PROTECT, to='expenses.m_status', verbose_name='ステータス')),
                ('expense_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='expenses.t_expensemain', verbose_name='経費申請')),
            ],
        ),
        migrations.CreateModel(
            name='M_BelongTo',
            fields=[
                ('belong_id', models.AutoField(primary_key=True, serialize=False, verbose_name='所属ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('man_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs', to=settings.AUTH_USER_MODEL, to_field='man_number', verbose_name='社員')),
                ('group_cd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.m_group', verbose_name='所属部署')),
            ],
            options={
                'verbose_name': '所属部署マッピング',
                'verbose_name_plural': '所属部署マッピング',
                'db_table': 'm_belong_to',
                'ordering': ['man_number', 'group_cd'],
                'unique_together': {('man_number', 'group_cd')},
            },
        ),
    ]
