# Generated by Django 5.2.6 on 2025-09-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_expensemain',
            name='bumon_cd',
            field=models.ForeignKey(blank=True, db_column='bumon_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.m_bumon', verbose_name='負担部門'),
        ),
    ]
