# Generated by Django 5.2.6 on 2025-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_t_expensemain_bumon_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_expensemain',
            name='memo',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='備考'),
        ),
    ]
