# Generated by Django 5.2.6 on 2025-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_t_expensedetail_tekikakusha_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_expensemain',
            name='pay_kbn',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='精算方法'),
        ),
        migrations.CreateModel(
            name='M_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_kbn', models.CharField(max_length=4, verbose_name='データ区分')),
                ('key', models.CharField(max_length=4, verbose_name='キー')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('content2', models.CharField(blank=True, max_length=50, verbose_name='内容2')),
            ],
            options={
                'verbose_name': '汎用項目マスタ',
                'verbose_name_plural': '汎用項目マスタ',
                'db_table': 'm_item',
                'constraints': [models.UniqueConstraint(fields=('data_kbn', 'key'), name='uq_m_item_data_kbn_key')],
            },
        ),
    ]
