# Generated by Django 5.2.6 on 2025-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_t_expensemain_pay_kbn_m_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_item',
            name='content',
            field=models.CharField(blank=True, max_length=50, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='m_item',
            name='content2',
            field=models.CharField(max_length=50, verbose_name='内容2'),
        ),
    ]
