# Generated by Django 5.2.6 on 2025-10-03 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_table_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_WorkflowTemplate',
            fields=[
                ('workflow_template_id', models.AutoField(db_column='workflow_template_id', primary_key=True, serialize=False, verbose_name='ワークフローテンプレートID')),
                ('workflow_template_name', models.CharField(max_length=100, verbose_name='ワークフローテンプレート名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'ワークフローテンプレートマスタ',
                'verbose_name_plural': 'ワークフローテンプレートマスタ',
                'db_table': 'm_workflow_templates',
            },
        ),
        migrations.AlterModelOptions(
            name='m_user',
            options={},
        ),
        migrations.AlterField(
            model_name='m_item',
            name='data_kbn',
            field=models.CharField(blank=True, max_length=4, verbose_name='データ区分'),
        ),
        migrations.AlterField(
            model_name='m_item',
            name='key',
            field=models.CharField(blank=True, max_length=4, verbose_name='キー'),
        ),
        migrations.CreateModel(
            name='M_WorkflowStep',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ステップID')),
                ('step_order', models.IntegerField(verbose_name='順序')),
                ('step_type', models.CharField(choices=[('approval', '承認'), ('reception', '受付'), ('confirmation', '確認')], default='approval', max_length=13, verbose_name='ステップ種別')),
                ('condition_expr', models.CharField(blank=True, max_length=255, null=True, verbose_name='条件式')),
                ('group_id', models.IntegerField(blank=True, null=True, verbose_name='グループID')),
                ('allowed_bumon_scope', models.CharField(choices=[('same', '同一'), ('parent', '親'), ('any', '全体')], default='any', max_length=7, verbose_name='部門許可範囲')),
                ('allowed_post', models.ForeignKey(blank=True, db_column='allowed_post_cd', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_workflow_steps', to='expenses.m_post', verbose_name='許可役職')),
                ('approver_post', models.ForeignKey(blank=True, db_column='approver_post_cd', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver_workflow_steps', to='expenses.m_post', verbose_name='承認者役職')),
                ('workflow_template', models.ForeignKey(db_column='workflow_template_id', on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='expenses.m_workflowtemplate', verbose_name='ワークフローテンプレート')),
            ],
            options={
                'verbose_name': 'ワークフローステップマスタ',
                'verbose_name_plural': 'ワークフローステップマスタ',
                'db_table': 'm_workflow_steps',
                'ordering': ['workflow_template', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='M_DocumentType',
            fields=[
                ('document_type_id', models.AutoField(db_column='document_type_id', primary_key=True, serialize=False, verbose_name='文書種別ID')),
                ('document_type_name', models.CharField(max_length=100, verbose_name='文書種別名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('workflow_template_id', models.ForeignKey(blank=True, db_column='workflow_template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.m_workflowtemplate', verbose_name='ワークフローテンプレート')),
            ],
            options={
                'verbose_name': '文書種別マスタ',
                'verbose_name_plural': '文書種別マスタ',
                'db_table': 'm_document_types',
            },
        ),
        migrations.CreateModel(
            name='T_WorkflowInstance',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='インスタンスID')),
                ('document_id', models.IntegerField(db_index=True, verbose_name='文書ID')),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('completed', '完了'), ('rejected', '却下'), ('returned', '差戻し')], default='in_progress', max_length=12, verbose_name='ステータス')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('workflow_template', models.ForeignKey(db_column='workflow_template_id', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='expenses.m_workflowtemplate', verbose_name='ワークフローテンプレート')),
            ],
            options={
                'verbose_name': 'ワークフローインスタンス',
                'verbose_name_plural': 'ワークフローインスタンス',
                'db_table': 'workflow_instances',
            },
        ),
        migrations.CreateModel(
            name='T_WorkflowAction',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False, verbose_name='アクションID')),
                ('action', models.CharField(choices=[('approved', '承認'), ('rejected', '却下'), ('returned', '差戻し')], max_length=8, verbose_name='操作')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('actioned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='処理日時')),
                ('approver_man_number', models.ForeignKey(db_column='approver_man_number', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='man_number', verbose_name='承認者社員番号')),
                ('step', models.ForeignKey(db_column='step_id', on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='expenses.m_workflowstep', verbose_name='対象ステップ')),
                ('instance', models.ForeignKey(db_column='instance_id', on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='expenses.t_workflowinstance', verbose_name='ワークフローインスタンス')),
            ],
            options={
                'verbose_name': 'ワークフローアクション',
                'verbose_name_plural': 'ワークフローアクション',
                'db_table': 't_workflow_actions',
                'ordering': ['-actioned_at'],
            },
        ),
    ]
