# Generated by Django 5.2.6 on 2025-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_m_workflowtemplate_alter_m_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_User',
            fields=[
                ('man_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='社員番号')),
                ('user_name', models.CharField(max_length=30, verbose_name='氏名')),
                ('group_cd', models.CharField(blank=True, max_length=20, null=True, verbose_name='部署コード')),
                ('group_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='部署名')),
                ('bumon_cd', models.CharField(blank=True, max_length=15, null=True, verbose_name='部門コード')),
                ('bumon_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='部門名')),
                ('post_cd', models.CharField(blank=True, max_length=15, null=True, verbose_name='役職コード')),
                ('post_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='役職名')),
            ],
            options={
                'verbose_name': 'ユーザビュー',
                'verbose_name_plural': 'ユーザビュー',
                'db_table': 'v_user',
                'managed': False,
            },
        ),
    ]
