# Generated by Django 5.2.6 on 2025-10-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_v_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_workflowinstance',
            options={'managed': False, 'verbose_name': 'ワークフローインスタンス', 'verbose_name_plural': 'ワークフローインスタンス'},
        ),
    ]
