# Generated by Django 5.2.6 on 2025-10-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_t_workflowinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_workflowinstance',
            options={'verbose_name': 'ワークフローインスタンス', 'verbose_name_plural': 'ワークフローインスタンス'},
        ),
    ]
