# Generated by Django 5.2.6 on 2025-10-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_t_workflowinstance_options'),
    ]

    operations = [
        # ベンダー非依存のCreateModelでテーブルを作成（MySQL専用SQLを排除）
        migrations.CreateModel(
            name='T_DocumentApprover',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.BigIntegerField(db_index=True, verbose_name='文書ID')),
                ('step_id', models.BigIntegerField(verbose_name='ステップID')),
                ('man_number', models.BigIntegerField(verbose_name='社員番号')),
                ('step_order', models.IntegerField(verbose_name='ステップ順')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='ステータス')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '文書承認者',
                'verbose_name_plural': '文書承認者',
                'db_table': 't_document_approvers',
            },
        ),
    ]
