# Generated by Django 5.2.6 on 2025-10-03 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_t_documentapprover_alter_t_workflowinstance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_documentapprover',
            name='document_id',
            field=models.ForeignKey(db_column='document_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='document_approvers', to='expenses.t_expensemain', verbose_name='文書'),
        ),
        migrations.AlterField(
            model_name='t_documentapprover',
            name='man_number',
            field=models.ForeignKey(db_column='man_number', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='document_approvals', to=settings.AUTH_USER_MODEL, to_field='man_number', verbose_name='承認者'),
        ),
        migrations.AlterField(
            model_name='t_documentapprover',
            name='step_id',
            field=models.ForeignKey(db_column='step_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='document_approvers', to='expenses.m_workflowstep', verbose_name='ステップ'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='t_workflowinstance',
                    table='t_workflow_instances',
                ),
            ],
        ),
    ]
