# Generated by Django 5.2.6 on 2025-10-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_reorder_columns_m_workflow_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_workflowstep',
            name='allowed_bumon_scope',
            field=models.CharField(choices=[('same', '同一'), ('parent', '親'), ('keiri', '経理'), ('any', '全体')], default='any', max_length=7, verbose_name='部門許可範囲'),
        ),
    ]
