# Generated by Django 5.2.6 on 2025-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_alter_m_workflowstep_allowed_bumon_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_post',
            name='post_order',
            field=models.IntegerField(default=0, help_text='小さいほど上位の扱い', verbose_name='職位順'),
        ),
    ]
