# Generated by Django 5.2.6 on 2025-10-08 00:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_m_post_post_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Document',
            fields=[
                ('document_id', models.AutoField(db_column='document_id', primary_key=True, serialize=False, verbose_name='文書ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('document_type', models.ForeignKey(db_column='document_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='expenses.m_documenttype', verbose_name='文書種別')),
                ('man_number', models.ForeignKey(db_column='man_number', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL, to_field='man_number', verbose_name='申請者')),
                ('bumon_cd', models.ForeignKey(blank=True, db_column='bumon_cd', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='expenses.m_bumon', verbose_name='部門')),
                ('status_cd', models.ForeignKey(db_column='status_cd_id', on_delete=django.db.models.deletion.PROTECT, to='expenses.m_status', verbose_name='ステータス')),
            ],
            options={
                'verbose_name': '文書',
                'verbose_name_plural': '文書',
                'db_table': 't_documents',
            },
        ),
    ]
