# Generated by Django 5.2.6 on 2025-10-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_t_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_DocumentContent',
            fields=[
                ('document_detail_id', models.AutoField(db_column='document_detail_id', primary_key=True, serialize=False, verbose_name='明細ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('tekikaku_cd', models.CharField(blank=True, max_length=15, null=True, verbose_name='登録番号')),
                ('shiharaisaki', models.CharField(blank=True, max_length=255, null=True, verbose_name='支払先')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='目的')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='金額')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/documents/%Y/%m/%d/', verbose_name='領収書')),
                ('receipt_thumbnail', models.ImageField(blank=True, null=True, upload_to='receipts/documents/%Y/%m/%d/thumbnails/', verbose_name='サムネイル')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='内容JSON')),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_contents', to='expenses.m_account', verbose_name='勘定科目')),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='expenses.t_document', verbose_name='文書')),
            ],
            options={
                'verbose_name': '文書明細',
                'verbose_name_plural': '文書明細',
                'db_table': 't_documentcontents',
            },
        ),
    ]
