# Generated by Django 5.2.6 on 2025-10-08 00:00
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_t_documentcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_workflowinstance',
            name='document_id',
            field=models.ForeignKey(db_column='document_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='expenses.t_document', verbose_name='文書'),
        ),
        migrations.AlterField(
            model_name='t_documentapprover',
            name='document_id',
            field=models.ForeignKey(db_column='document_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='document_approvers', to='expenses.t_document', verbose_name='文書'),
        ),
        # 既存データとの整合性のため、DB制約を張らずに状態のみ T_Document 参照に切替
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='t_approvallog',
                    name='expense_main',
                    field=models.ForeignKey(db_column='expense_main_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='expenses.t_document', verbose_name='文書'),
                ),
            ]
        ),
    ]
