# Generated by Django 5.2.6 on 2025-10-08 15:09

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_replace_fk_to_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_documentcontent',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=expenses.models.document_receipt_upload_path, verbose_name='領収書'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='receipt_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=expenses.models.document_thumbnail_upload_path, verbose_name='サムネイル'),
        ),
    ]
