# Generated by Django 5.2.6 on 2025-10-17 15:32

import django.db.models.deletion
from django.db import migrations, models


def rename_workflow_instances_table(apps, schema_editor):
    conn = schema_editor.connection
    vendor = conn.vendor
    existing = set(conn.introspection.table_names())
    old = 'workflow_instances'
    new = 't_workflow_instances'
    if old in existing and new not in existing:
        with conn.cursor() as cursor:
            if vendor == 'mysql':
                cursor.execute("RENAME TABLE `workflow_instances` TO `t_workflow_instances`;")
            else:
                cursor.execute('ALTER TABLE "workflow_instances" RENAME TO "t_workflow_instances";')


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_alter_t_documentcontent_receipt_and_more'),
    ]

    operations = [
        migrations.RunPython(code=rename_workflow_instances_table, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='t_workflowinstance',
            name='step',
            field=models.ForeignKey(blank=True, db_column='step_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances_current', to='expenses.m_workflowstep', verbose_name='現在ステップ'),
        ),
        migrations.AddField(
            model_name='t_workflowinstance',
            name='step_order',
            field=models.IntegerField(blank=True, db_column='step_order', null=True, verbose_name='現在ステップ順'),
        ),
    ]
