# Generated by Django 5.2.6 on 2025-10-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021a_fix_workflowinstance_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workflowinstance',
            name='step',
            field=models.ForeignKey(blank=True, db_column='step_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances_current', to='expenses.m_workflowstep', verbose_name='現在ステップ'),
        ),
        migrations.AddField(
            model_name='t_workflowinstance',
            name='step_order',
            field=models.IntegerField(blank=True, db_column='step_order', null=True, verbose_name='現在ステップ順'),
        ),
    ]
