# Generated by Django 5.2.6 on 2025-10-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_t_workflowinstance_step_and_more'),
    ]

    operations = [
        # action_name は既にDBに存在する環境があるため、状態のみ追加しDB操作は行わない
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='m_status',
                    name='action_name',
                    field=models.CharField(blank=True, max_length=50, null=True, verbose_name='アクション名'),
                ),
            ],
            database_operations=[],
        ),
        # 旧テーブル/カラムが既に欠落しているDBに対応するため、
        # RemoveField / DeleteModel もDB操作を行わず状態だけを前進させる
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='t_expensemain',
                    name='applicant',
                ),
                migrations.RemoveField(
                    model_name='t_expensemain',
                    name='approver_man_number_1',
                ),
                migrations.RemoveField(
                    model_name='t_expensemain',
                    name='approver_man_number_2',
                ),
                migrations.RemoveField(
                    model_name='t_expensemain',
                    name='bumon_cd',
                ),
                migrations.RemoveField(
                    model_name='t_expensemain',
                    name='status_cd',
                ),
                migrations.DeleteModel(
                    name='T_ExpenseDetail',
                ),
                migrations.DeleteModel(
                    name='T_ExpenseMain',
                ),
            ],
            database_operations=[],
        ),
    ]
