# Generated by Django 5.2.6 on 2025-10-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_remove_t_expensemain_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_workflowaction',
            name='action',
        ),
        migrations.AddField(
            model_name='t_workflowaction',
            name='action_status',
            field=models.ForeignKey(blank=True, db_column='action', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.m_status', verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='t_workflowinstance',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.m_status', verbose_name='ステータス'),
        ),
    ]
