# Generated by Django 5.2.6 on 2025-10-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_remove_t_workflowaction_action_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T_ApprovalLog',
        ),
    ]
