# Generated by Django 5.2.6 on 2025-10-19 16:17

import django.db.models.deletion
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_delete_t_approvallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_DocumentAttachment',
            fields=[
                ('attachment_id', models.AutoField(db_column='attachment_id', primary_key=True, serialize=False, verbose_name='添付ID')),
                ('file', models.FileField(upload_to=expenses.models.attachment_upload_path, verbose_name='添付ファイル')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=expenses.models.attachment_thumbnail_upload_path, verbose_name='サムネイル')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('detail', models.ForeignKey(db_column='document_detail_id', on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='expenses.t_documentcontent', verbose_name='明細')),
            ],
            options={
                'verbose_name': '文書添付',
                'verbose_name_plural': '文書添付',
                'db_table': 't_document_attachments',
            },
        ),
    ]
