# Generated by Django 5.2.6 on 2025-10-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_t_documentattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_documentcontent',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='t_documentcontent',
            name='receipt_thumbnail',
        ),
    ]
