# Generated by Django 5.2.6 on 2025-10-27 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_squashed_0026_remove_t_documentcontent_receipt_and_more'),
    ]

    operations = [
        # MySQL で既存のインデックス名が衝突するケースを回避
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda: (
                    (lambda conn: (
                        (lambda vendor: (
                            None if vendor != 'mysql' else (
                                (lambda cursor: (
                                    cursor.execute("SHOW INDEX FROM `t_workflow_instances` WHERE Key_name=%s", ('t_workflow_instances_status_c25c5b05',)),
                                    cursor.fetchone() and cursor.execute("DROP INDEX `t_workflow_instances_status_c25c5b05` ON `t_workflow_instances`")
                                ))(conn.cursor())
                            )
                        ))(conn.vendor)
                    ))(schema_editor.connection)
                ))()
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='t_workflowinstance',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.m_status', verbose_name='ステータス'),
        ),
    ]
