# Generated by Django 5.2.6 on 2025-10-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_alter_t_workflowinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_document',
            name='tsuka_cd',
            field=models.CharField(max_length=3, db_column='tsuka_cd', verbose_name='通貨コード', blank=True, null=True),
        ),
    ]
