# Generated by Django 5.2.6 on 2025-11-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0028_add_t_document_tsuka_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_document',
            name='ringi_no',
            field=models.CharField(blank=True, db_column='ringi_no', max_length=20, null=True, verbose_name='稟議No'),
        ),
    ]
