# Generated by Django 5.2.6 on 2025-11-16 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0029_t_document_ringi_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30, verbose_name='フィールド名')),
                ('field_type', models.CharField(max_length=30, verbose_name='フィールド型')),
                ('document_type', models.ForeignKey(db_column='document_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='document_fields', to='expenses.m_documenttype', verbose_name='文書種別')),
            ],
            options={
                'verbose_name': '文書フィールドマスタ',
                'verbose_name_plural': '文書フィールドマスタ',
                'db_table': 'm_document_field',
                'ordering': ['document_type', 'field_name'],
                'unique_together': {('document_type', 'field_name')},
            },
        ),
    ]
