# Generated by Django 5.2.6 on 2025-11-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_m_documentfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_documentfield',
            name='field_name_view',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='表示名'),
        ),
    ]
