# Generated by Django 5.2.6 on 2026-03-23 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0031_m_documentfield_field_name_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_AccountDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_cd', models.ForeignKey(db_column='account_cd', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='account_documents', to='expenses.m_account', verbose_name='勘定科目')),
                ('document_type', models.ForeignKey(db_column='document_type_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='account_documents', to='expenses.m_documenttype', verbose_name='文書種別')),
            ],
            options={
                'verbose_name': '文書種別勘定科目マスタ',
                'verbose_name_plural': '文書種別勘定科目マスタ',
                'db_table': 'm_account_document',
                'ordering': ['document_type', 'account_cd'],
                'unique_together': {('document_type', 'account_cd')},
            },
        ),
    ]
