# Generated by Django 5.2.6 on 2026-03-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0032_add_m_account_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_documentcontent',
            name='corpo_card',
            field=models.IntegerField(blank=True, null=True, verbose_name='コーポレートカード支払い'),
        ),
    ]
