# Generated by Django 5.2.6 on 2026-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0033_add_corpo_card_to_documentcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_documentcontent',
            name='corpo_card_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='カード番号'),
        ),
    ]
