# Generated by Django 5.2.6 on 2026-03-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0035_m_documentfield_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_documenttype',
            name='bumon_scope',
            field=models.SmallIntegerField(choices=[(0, '自グループ絞り込み'), (1, '全部門')], default=0, help_text='0: 自グループ絞り込み / 1: 全部門表示', verbose_name='負担部門スコープ'),
        ),
    ]
