# Generated by Django 5.2.6 on 2026-05-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0041_t_document_pay_kbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_documenttype',
            name='category',
            field=models.CharField(choices=[('expense', '費用精算'), ('asset', '固定資産')], default='expense', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
