# Generated by Django 5.2.6 on 2026-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0042_add_category_to_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_documentfield',
            name='section_header',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='セクション見出し'),
        ),
        migrations.AlterField(
            model_name='m_documenttype',
            name='category',
            field=models.CharField(choices=[('expense', '費用精算'), ('assets', '固定資産')], default='expense', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
