# Generated by Django 5.2.6 on 2026-05-18 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0043_add_section_header_to_document_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False, verbose_name='要望ID')),
                ('request_text', models.CharField(max_length=100, verbose_name='要望事項')),
                ('response_text', models.CharField(blank=True, default='', max_length=100, verbose_name='回答')),
                ('status_cd', models.CharField(choices=[('00', '受付中'), ('01', '検討中'), ('02', '対応済'), ('03', '対応不可')], default='00', max_length=2, verbose_name='状況')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('man_number', models.ForeignKey(blank=True, db_column='man_number', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to=settings.AUTH_USER_MODEL, to_field='man_number', verbose_name='申請者')),
            ],
            options={
                'verbose_name': '改善要望',
                'verbose_name_plural': '改善要望',
                'db_table': 't_feedback',
                'ordering': ['-created_at', '-feedback_id'],
            },
        ),
    ]
