# Generated by Django 5.2.6 on 2026-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0053_add_T_ASSETS'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_assets',
            name='account_cd',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='科目コード'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='account_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='accounting_bumon_cd',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='会計用部門コード'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='alloc_kbn',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='部門配賦区分'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='alloc_rate_cd',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='配賦率コード'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='asset_name1',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='資産名１'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='asset_name2',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='資産名２'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='bumon_cd',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='部門コード'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='bumon_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='部門名'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='city_cd',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='市区町村コード'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='city_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='市区町村名'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='collateral_kbn',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='担保資産区分'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='decrease_kbn',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='減少区分'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='detail_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='細目名'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='disposal_kbn',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='除却区分'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='extra_depreciation_kbn',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='割増償却計算区分'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='increase_reason',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='増加事由'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='location_cd',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='設置場所コード'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='location_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='設置場所名'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='manager',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='memo1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='メモ欄'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='memo2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='メモ欄２'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='model_name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='モデル'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='partial_expansion_asset_cd',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='一部増設元資産コード'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='physical_inventory_result',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='実地調査結果'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='ringi_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='稟議NO'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='serial_no',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='シリアルNO'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='source_asset_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='異動元資産NO'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='special_depreciation_kbn',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='特別償却計算区分'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='structure_cd',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='構造細目コード'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='structure_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='構造名'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='supplier_cd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='購入先コード'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='tax_target_kbn',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='納税対象区分'),
        ),
        migrations.AlterField(
            model_name='t_assets',
            name='unit',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='単位'),
        ),
    ]
