# Generated by Django 5.2.6 on 2026-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0056_remove_obsolete_m_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_user',
            name='extra_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='追加権限'),
        ),
    ]
