# Generated by Django 5.2.6 on 2026-05-30 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0057_add_extra_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_user',
            name='extra_roles',
        ),
        migrations.CreateModel(
            name='M_UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='ロール')),
                ('man_number', models.ForeignKey(db_column='man_number', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, to_field='man_number', verbose_name='社員番号')),
            ],
            options={
                'verbose_name': 'ユーザーロール',
                'verbose_name_plural': 'ユーザーロール',
                'db_table': 'm_user_role',
                'unique_together': {('man_number', 'role')},
            },
        ),
    ]
