# Generated by Django 5.2.6 on 2026-06-01 07:06

import warnings
from django.db import migrations, models
from expenses.view_sqls import ALL_VIEWS


def recreate_v_documentcontents(apps, schema_editor):
    with schema_editor.connection.cursor() as cur:
        try:
            cur.execute(ALL_VIEWS['v_documentcontents'])
        except Exception as e:
            warnings.warn(f"[0060] v_documentcontents VIEW の再作成をスキップ ({e})")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0059_remove_role_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_documentcontent',
            name='settle_kbn',
            field=models.CharField(blank=True, db_column='settle_kbn', max_length=10, null=True, verbose_name='精算区分'),
        ),
        migrations.RunPython(recreate_v_documentcontents, reverse_code=noop),
    ]
