# Generated by Django 5.2.6 on 2026-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0060_add_settle_kbn_to_documentcontents'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_status',
            name='status_kbn',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='ステータス区分'),
        ),
    ]
