# Generated by Django 5.2.6 on 2026-06-02 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0065_add_m_mail_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Settle',
            fields=[
                ('settle_id', models.AutoField(primary_key=True, serialize=False, verbose_name='精算ログID')),
                ('status_cd', models.CharField(blank=True, max_length=20, null=True, verbose_name='精算ステータス')),
                ('settle_ymd', models.DateField(blank=True, null=True, verbose_name='精算日')),
                ('create_ymd', models.DateField(auto_now_add=True, verbose_name='登録日')),
                ('update_ymd', models.DateField(auto_now=True, verbose_name='更新日')),
                ('document', models.ForeignKey(db_column='document_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='settle_logs', to='expenses.t_document', verbose_name='文書')),
                ('document_detail', models.ForeignKey(blank=True, db_column='document_detail_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settle_logs', to='expenses.t_documentcontent', verbose_name='明細')),
                ('man_number', models.ForeignKey(blank=True, db_column='man_number', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settle_logs', to=settings.AUTH_USER_MODEL, to_field='man_number', verbose_name='処理者')),
            ],
            options={
                'verbose_name': '精算ログ',
                'verbose_name_plural': '精算ログ',
                'db_table': 't_settle',
                'ordering': ['-create_ymd', '-settle_id'],
            },
        ),
    ]
