# Generated by Django 5.2.6 on 2026-06-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0066_add_t_settle'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_bumon',
            name='cs_kbn',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='CS区分'),
        ),
    ]
