# Generated by Django 5.2.6 on 2026-06-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0068_create_v_settle'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_documentcontent',
            name='consumption_kbn',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='内外税区分'),
        ),
        migrations.AddField(
            model_name='t_documentcontent',
            name='consumption_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='消費税額'),
        ),
    ]
