# Generated by Django 5.2.6 on 2026-06-02 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0069_add_consumption_fields_to_documentcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_DocumentEditHistory',
            fields=[
                ('edit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='修正ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='フィールド名')),
                ('field_label', models.CharField(blank=True, max_length=100, verbose_name='フィールドラベル')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='変更前')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='変更後')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='修正日時')),
                ('detail', models.ForeignKey(blank=True, db_column='document_detail_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_histories', to='expenses.t_documentcontent', verbose_name='明細')),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='edit_histories', to='expenses.t_document', verbose_name='文書')),
                ('man_number', models.ForeignKey(db_column='man_number', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='man_number', verbose_name='修正者')),
            ],
            options={
                'verbose_name': '経費修正履歴',
                'verbose_name_plural': '経費修正履歴',
                'db_table': 't_document_edit_history',
                'ordering': ['-edited_at'],
            },
        ),
    ]
