# Generated by Django 5.2.6 on 2026-06-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0070_add_document_edit_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='m_user',
            name='user_permissions',
        ),
    ]
