# Generated by Django 6.0.5 on 2026-06-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0078_remove_hojo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_documentcontent',
            name='journal_fx_tax',
        ),
        migrations.AlterField(
            model_name='m_accountsub',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
