# Generated by Django 6.0.5 on 2026-06-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0079_remove_journal_fx_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ExchengRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keijyo_ym', models.CharField(max_length=6, verbose_name='計上年月')),
                ('tsuka_cd', models.CharField(max_length=3, verbose_name='通貨コード')),
                ('exchenge_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='換算レート')),
            ],
            options={
                'verbose_name': '換算為替レート',
                'verbose_name_plural': '換算為替レート',
                'db_table': 'M_ExchengRate',
                'unique_together': {('keijyo_ym', 'tsuka_cd')},
            },
        ),
    ]
