# Generated by Django 6.0.5 on 2026-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0091_fix_t_assets_column_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_AssetsLowValue',
            fields=[
                ('low_value_asset_no', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='小額資産番号')),
                ('maker_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='メーカー名')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                ('model_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='品番')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='製造番号')),
                ('purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='用途')),
                ('acquisition_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='取得価格')),
                ('acquisition_date', models.DateTimeField(blank=True, null=True, verbose_name='年月日')),
                ('bumon_cd', models.CharField(blank=True, max_length=10, null=True, verbose_name='部門コード')),
                ('bumon_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='部門名')),
                ('location_cd', models.CharField(blank=True, max_length=10, null=True, verbose_name='設置場所コード')),
                ('location_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='設置場所名')),
                ('cre_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('up_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '少額資産',
                'verbose_name_plural': '少額資産',
                'db_table': 't_assets_low_value',
                'ordering': ['low_value_asset_no'],
            },
        ),
    ]
