# Generated by Django 5.2.6 on 2026-07-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0096_update_v_journaldocuments_account_cd5'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_documentcontent',
            name='split_from',
            field=models.ForeignKey(blank=True, db_column='split_from_id', db_comment='仕訳分割の元明細ID（NULL=通常明細）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.t_documentcontent', verbose_name='分割元明細'),
        ),
    ]
