# Generated by Django 5.2.6 on 2026-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0099_add_journal_amount_incl_to_v_journaldocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_document',
            name='settled_at',
            field=models.DateTimeField(blank=True, db_column='settled_at', help_text='精算処理を開始した日（未精算データ分類画面で設定）。精算完了日ではない。', null=True, verbose_name='精算開始日時'),
        ),
    ]
