# Generated by Django 6.0.5 on 2026-07-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0102_v_journaldocuments_add_settled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_documentcontent',
            name='item_cd',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='品目コード'),
        ),
        migrations.AddField(
            model_name='t_documentcontent',
            name='supplier_cd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='仕入先コード'),
        ),
    ]
