# Generated by Django 6.0.5 on 2026-07-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0103_add_supplier_item_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_documentcontent',
            name='qty',
            field=models.IntegerField(blank=True, db_column='Qty', null=True, verbose_name='数量'),
        ),
    ]
