# Generated by Django 5.2.6 on 2026-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0105_add_supplier_item_qty_to_journal_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='GS_Group',
            fields=[
                ('grp_sid', models.IntegerField(primary_key=True, serialize=False, verbose_name='旧グループSID')),
                ('grp_id', models.CharField(max_length=50, verbose_name='グループID')),
                ('grp_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='グループ名')),
                ('grp_name_kn', models.CharField(blank=True, max_length=75, null=True, verbose_name='グループ名カナ')),
                ('grp_comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='コメント')),
                ('grp_auid', models.IntegerField(verbose_name='作成者旧USR_SID')),
                ('grp_adate', models.DateTimeField(verbose_name='作成日時')),
                ('grp_euid', models.IntegerField(verbose_name='更新者旧USR_SID')),
                ('grp_edate', models.DateTimeField(verbose_name='更新日時')),
                ('grp_sort', models.IntegerField(verbose_name='表示順')),
                ('grp_jkbn', models.IntegerField(verbose_name='状態区分')),
            ],
            options={
                'verbose_name': '旧組織グループ(GSESSION)',
                'verbose_name_plural': '旧組織グループ(GSESSION)',
                'db_table': 'GS_GROUP',
                'ordering': ['grp_sort', 'grp_sid'],
            },
        ),
        migrations.CreateModel(
            name='GS_Position',
            fields=[
                ('pos_sid', models.IntegerField(primary_key=True, serialize=False, verbose_name='旧役職SID')),
                ('pos_code', models.CharField(max_length=15, verbose_name='役職コード')),
                ('pos_name', models.CharField(max_length=30, verbose_name='役職名')),
                ('pos_biko', models.CharField(blank=True, max_length=300, verbose_name='備考')),
                ('pos_sort', models.IntegerField(verbose_name='表示順')),
                ('pos_auid', models.IntegerField(verbose_name='作成者旧USR_SID')),
                ('pos_adate', models.DateTimeField(verbose_name='作成日時')),
                ('pos_euid', models.IntegerField(verbose_name='更新者旧USR_SID')),
                ('pos_edate', models.DateTimeField(verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '旧役職(GSESSION)',
                'verbose_name_plural': '旧役職(GSESSION)',
                'db_table': 'GS_POSITION',
                'ordering': ['pos_sort', 'pos_sid'],
            },
        ),
        migrations.CreateModel(
            name='GS_Ringi',
            fields=[
                ('rng_sid', models.IntegerField(primary_key=True, serialize=False, verbose_name='旧稟議SID')),
                ('rng_title', models.CharField(max_length=100, verbose_name='件名')),
                ('rng_makedate', models.DateTimeField(verbose_name='作成日時')),
                ('rng_applicate', models.IntegerField(blank=True, null=True, verbose_name='申請者旧USR_SID')),
                ('rng_appldate', models.DateTimeField(blank=True, null=True, verbose_name='申請日時')),
                ('rng_status', models.IntegerField(verbose_name='ステータス')),
                ('rng_compflg', models.IntegerField(verbose_name='完了フラグ')),
                ('rng_admcomment', models.CharField(blank=True, max_length=300, null=True, verbose_name='管理者コメント')),
                ('rng_auid', models.IntegerField(verbose_name='作成者旧USR_SID')),
                ('rng_adate', models.DateTimeField(verbose_name='作成日時(監査)')),
                ('rng_euid', models.IntegerField(verbose_name='更新者旧USR_SID')),
                ('rng_edate', models.DateTimeField(verbose_name='更新日時(監査)')),
                ('rng_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='表示用ID')),
                ('rtp_sid', models.IntegerField(verbose_name='テンプレート旧SID')),
                ('rtp_ver', models.IntegerField(verbose_name='テンプレートバージョン')),
                ('rct_ver', models.IntegerField(default=0, verbose_name='カテゴリバージョン')),
            ],
            options={
                'verbose_name': '旧稟議データ(GSESSION)',
                'verbose_name_plural': '旧稟議データ(GSESSION)',
                'db_table': 'GS_RINGI',
                'ordering': ['-rng_sid'],
            },
        ),
        migrations.CreateModel(
            name='GS_Usr',
            fields=[
                ('usr_sid', models.IntegerField(primary_key=True, serialize=False, verbose_name='旧ユーザーSID')),
                ('usr_lgid', models.CharField(max_length=256, verbose_name='ログインID')),
                ('usr_jkbn', models.IntegerField(verbose_name='在籍区分')),
                ('usi_sei', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓')),
                ('usi_mei', models.CharField(blank=True, max_length=30, null=True, verbose_name='名')),
                ('usi_sei_kn', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓カナ')),
                ('usi_mei_kn', models.CharField(blank=True, max_length=60, null=True, verbose_name='名カナ')),
                ('usi_syain_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='社員番号')),
                ('usi_syozoku', models.CharField(blank=True, max_length=60, null=True, verbose_name='所属名')),
                ('usi_yakusyoku', models.CharField(blank=True, max_length=30, null=True, verbose_name='役職名')),
                ('pos_sid', models.IntegerField(blank=True, null=True, verbose_name='旧役職SID')),
                ('usi_entrance_date', models.DateTimeField(blank=True, null=True, verbose_name='入社日')),
            ],
            options={
                'verbose_name': '旧ユーザー(GSESSION)',
                'verbose_name_plural': '旧ユーザー(GSESSION)',
                'db_table': 'GS_USR',
                'ordering': ['usr_sid'],
            },
        ),
        migrations.CreateModel(
            name='GS_Belong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_sid', models.IntegerField(verbose_name='旧グループSID')),
                ('usr_sid', models.IntegerField(verbose_name='旧ユーザーSID')),
                ('beg_auid', models.IntegerField(verbose_name='作成者旧USR_SID')),
                ('beg_adate', models.DateTimeField(verbose_name='作成日時')),
                ('beg_euid', models.IntegerField(verbose_name='更新者旧USR_SID')),
                ('beg_edate', models.DateTimeField(verbose_name='更新日時')),
                ('beg_defgrp', models.IntegerField(verbose_name='デフォルトグループ区分')),
                ('beg_grpkbn', models.IntegerField(blank=True, null=True, verbose_name='グループ区分')),
            ],
            options={
                'verbose_name': '旧所属(GSESSION)',
                'verbose_name_plural': '旧所属(GSESSION)',
                'db_table': 'GS_BELONG',
                'unique_together': {('grp_sid', 'usr_sid', 'beg_grpkbn')},
            },
        ),
    ]
