# Generated by Django 5.2.6 on 2026-07-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0106_gs2db_legacy_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gs_position',
            name='pos_biko',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='備考'),
        ),
    ]
