# Generated by Django 5.2.6 on 2026-07-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0107_gs_position_biko_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_adate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_auid',
            field=models.IntegerField(blank=True, null=True, verbose_name='作成者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_defgrp',
            field=models.IntegerField(blank=True, null=True, verbose_name='デフォルトグループ区分'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_edate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_euid',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='grp_sid',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧グループSID'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='usr_sid',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ユーザーSID'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_adate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_auid',
            field=models.IntegerField(blank=True, null=True, verbose_name='作成者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_edate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_euid',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='グループID'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_jkbn',
            field=models.IntegerField(blank=True, null=True, verbose_name='状態区分'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_adate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_auid',
            field=models.IntegerField(blank=True, null=True, verbose_name='作成者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='役職コード'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_edate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_euid',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='役職名'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rct_ver',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='カテゴリバージョン'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_adate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日時(監査)'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_auid',
            field=models.IntegerField(blank=True, null=True, verbose_name='作成者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_compflg',
            field=models.IntegerField(blank=True, null=True, verbose_name='完了フラグ'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_edate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日時(監査)'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_euid',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_makedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='件名'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rtp_sid',
            field=models.IntegerField(blank=True, null=True, verbose_name='テンプレート旧SID'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rtp_ver',
            field=models.IntegerField(blank=True, null=True, verbose_name='テンプレートバージョン'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usr_jkbn',
            field=models.IntegerField(blank=True, null=True, verbose_name='在籍区分'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usr_lgid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ログインID'),
        ),
        # GS_* テーブルは新規作成時にDjangoが utf8mb4_unicode_ci 以外のコレーションで
        # 作成する場合があるため、他の既存テーブルと統一する（CLAUDE.md「MySQLコレーション注意」参照）。
        migrations.RunSQL(
            sql="ALTER TABLE GS_RINGI CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE GS_USR CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE GS_GROUP CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE GS_BELONG CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE GS_POSITION CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
