# Generated by Django 5.2.6 on 2026-07-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0108_gs2db_fields_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='仕訳処理日時'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_done',
            field=models.SmallIntegerField(default=0, verbose_name='仕訳入力済'),
        ),
    ]
