# Generated by Django 5.2.6 on 2026-07-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0109_alter_t_documentcontent_journal_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_documentcontent',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', db_comment='勘定科目ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_contents', to='expenses.m_account', verbose_name='勘定科目'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='account_cd_cre',
            field=models.CharField(blank=True, db_comment='貸方科目コード', max_length=20, null=True, verbose_name='貸方科目コード'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='account_sub_cd_cre',
            field=models.CharField(blank=True, db_comment='貸方補助科目コード', max_length=10, null=True, verbose_name='貸方補助科目コード'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='amount',
            field=models.DecimalField(blank=True, db_comment='金額', decimal_places=2, max_digits=10, null=True, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='consumption_kbn',
            field=models.SmallIntegerField(blank=True, db_comment='内外税区分', null=True, verbose_name='内外税区分'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='consumption_tax',
            field=models.DecimalField(blank=True, db_comment='消費税額', decimal_places=2, max_digits=10, null=True, verbose_name='消費税額'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='content',
            field=models.JSONField(blank=True, db_comment='内容JSON', null=True, verbose_name='内容JSON'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='corpo_card',
            field=models.IntegerField(blank=True, db_comment='コーポレートカード支払い', null=True, verbose_name='コーポレートカード支払い'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='corpo_card_no',
            field=models.CharField(blank=True, db_comment='カード番号', max_length=10, null=True, verbose_name='カード番号'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='date',
            field=models.DateField(blank=True, db_comment='日付', null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='document',
            field=models.ForeignKey(db_column='document_id', db_comment='文書ID', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='expenses.t_document', verbose_name='文書'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='document_detail_id',
            field=models.AutoField(db_column='document_detail_id', db_comment='明細ID', primary_key=True, serialize=False, verbose_name='明細ID'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='hojo_cd',
            field=models.CharField(blank=True, db_comment='補助科目コード', max_length=10, null=True, verbose_name='補助科目コード'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='item_cd',
            field=models.CharField(blank=True, db_comment='品目コード', max_length=30, null=True, verbose_name='品目コード'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_amont',
            field=models.DecimalField(blank=True, db_comment='借方税抜金額', decimal_places=2, max_digits=10, null=True, verbose_name='借方税抜金額'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_amont_fx',
            field=models.DecimalField(blank=True, db_comment='借方税抜外貨', decimal_places=2, max_digits=10, null=True, verbose_name='借方税抜外貨'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_amont_fx_cre',
            field=models.DecimalField(blank=True, db_comment='貸方税抜外貨', decimal_places=2, max_digits=10, null=True, verbose_name='貸方税抜外貨'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_amount_cre',
            field=models.DecimalField(blank=True, db_comment='貸方税抜金額', decimal_places=2, max_digits=10, null=True, verbose_name='貸方税抜金額'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_at',
            field=models.DateTimeField(blank=True, db_comment='仕訳処理日時', null=True, verbose_name='仕訳処理日時'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_discription_cre',
            field=models.CharField(blank=True, db_comment='貸方摘要', max_length=50, null=True, verbose_name='貸方摘要'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_discription_deb',
            field=models.CharField(blank=True, db_comment='借方摘要', max_length=50, null=True, verbose_name='借方適用'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_done',
            field=models.SmallIntegerField(db_comment='仕訳入力ステータス（0=未入力, 1=入力済, 2=仕訳取込済み）', default=0, verbose_name='仕訳入力ステータス'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_fx_rate',
            field=models.CharField(blank=True, db_comment='換算レート', max_length=20, null=True, verbose_name='換算レート'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_tax',
            field=models.DecimalField(blank=True, db_comment='借方税額', decimal_places=2, max_digits=10, null=True, verbose_name='借方税額'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_tax_fx',
            field=models.DecimalField(blank=True, db_comment='借方税額外貨', decimal_places=2, max_digits=10, null=True, verbose_name='借方税額外貨'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_tax_kbn',
            field=models.CharField(blank=True, db_comment='仕訳税区分', max_length=10, null=True, verbose_name='仕訳税区分'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_tax_rate',
            field=models.CharField(blank=True, db_comment='仕訳税率', max_length=10, null=True, verbose_name='仕訳税率'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_tori_cd_cre',
            field=models.CharField(blank=True, db_comment='貸方取引先コード', max_length=10, null=True, verbose_name='貸方取引先コード'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='purpose',
            field=models.CharField(blank=True, db_comment='目的', max_length=255, null=True, verbose_name='目的'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='qty',
            field=models.IntegerField(blank=True, db_column='Qty', db_comment='数量', null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='settle_kbn',
            field=models.CharField(blank=True, db_column='settle_kbn', db_comment='精算区分', max_length=10, null=True, verbose_name='精算区分'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='shiharaisaki',
            field=models.CharField(blank=True, db_comment='支払先', max_length=255, null=True, verbose_name='支払先'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='supplier_cd',
            field=models.CharField(blank=True, db_comment='仕入先コード', max_length=10, null=True, verbose_name='仕入先コード'),
        ),
        migrations.AlterField(
            model_name='t_documentcontent',
            name='tekikaku_cd',
            field=models.CharField(blank=True, db_comment='登録番号（インボイス）', max_length=15, null=True, verbose_name='登録番号'),
        ),
    ]
