# Generated by Django 5.2.6 on 2026-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0110_alter_t_documentcontent_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_documentcontent',
            name='journal_discription_deb',
            field=models.CharField(blank=True, db_comment='借方摘要', max_length=50, null=True, verbose_name='借方摘要'),
        ),
    ]
