# Generated by Django 5.2.6 on 2026-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0114_unify_collation_0900_ai_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_user',
            name='username',
            field=models.CharField(help_text='150文字以内で入力してください。', max_length=150, unique=True, verbose_name='ユーザー名'),
        ),
    ]
