# Generated by Django 5.2.6 on 2026-07-29 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0115_alter_m_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_ChinaExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='注文番号')),
                ('supplier_cd', models.CharField(blank=True, max_length=10, null=True, verbose_name='仕入先コード')),
                ('supplier_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='仕入先名')),
                ('item_cd', models.CharField(blank=True, max_length=15, null=True, verbose_name='品目コード')),
                ('item_name1', models.CharField(max_length=50, verbose_name='品目名1')),
                ('item_name2', models.CharField(blank=True, max_length=50, null=True, verbose_name='品目名2')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='仕入単価')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='購入日')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='数量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('account_cd', models.CharField(blank=True, max_length=10, null=True, verbose_name='科目コード')),
                ('account_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='科目名')),
                ('burden_bumon_cd', models.CharField(blank=True, max_length=10, null=True, verbose_name='負担部門コード')),
                ('burden_bumon_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='負担部署名')),
                ('order_bumon_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='発注部署名')),
                ('order_staff_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='発注担当名')),
                ('export_planned_date', models.DateField(blank=True, null=True, verbose_name='輸出予定日')),
                ('export_date', models.DateField(blank=True, null=True, verbose_name='輸出日')),
                ('invoice_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='インボイスNo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '中国輸出実績報告',
                'verbose_name_plural': '中国輸出実績報告',
                'db_table': 't_china_export',
            },
        ),
    ]
