# Generated by Django 5.2.6 on 2026-07-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0116_t_chinaexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_chinaexport',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='仕入単価'),
        ),
    ]
