# Generated by Django 5.2.6 on 2026-07-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0117_alter_t_chinaexport_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_chinaexport',
            name='item_cd',
        ),
    ]
