# Generated by Django 5.2.6 on 2026-07-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0118_remove_t_chinaexport_item_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ExchangeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, verbose_name='アップロード先テーブル')),
                ('updata_title', models.CharField(max_length=100, verbose_name='読み込みファイルの見出し名')),
                ('up_field_name', models.CharField(max_length=100, verbose_name='書き出し先フィールド名')),
            ],
            options={
                'verbose_name': '見出し変換マスタ',
                'verbose_name_plural': '見出し変換マスタ',
                'db_table': 'm_exchange_fields',
                'unique_together': {('table_name', 'updata_title')},
            },
        ),
    ]
