# Generated by Django 5.2.6 on 2026-08-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0119_m_exchangefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_exchangefield',
            options={'ordering': ['table_name', 'updata_title'], 'verbose_name': '見出し変換マスタ', 'verbose_name_plural': '見出し変換マスタ'},
        ),
    ]
