# Generated by Django 5.2.6 on 2026-08-19 10:48

import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0120_alter_m_exchangefield_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_ChinaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_no', models.CharField(blank=True, max_length=20, unique=True, verbose_name='管理番号')),
                ('invoice_no', models.CharField(max_length=50, verbose_name='Invoice No')),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Invoice Total')),
                ('export_date', models.DateField(verbose_name='輸出日')),
                ('cargo_note', models.CharField(blank=True, max_length=200, verbose_name='貨物概要補足')),
                ('adjustment_rate_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='加算調整率')),
                ('invoice_file', models.FileField(upload_to=expenses.models.china_invoice_upload_path, verbose_name='Invoiceファイル')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('accounting_confirmed', models.BooleanField(default=False, verbose_name='経理確認')),
                ('accounting_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='経理確認日時')),
                ('china_confirm_status', models.CharField(choices=[('unconfirmed', '未確認'), ('confirmed', '確認済み'), ('difference', '差異あり')], default='unconfirmed', max_length=20, verbose_name='中国側確認')),
                ('china_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='中国側確認日時')),
                ('accounting_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='経理確認者')),
                ('cargo_category', models.ForeignKey(limit_choices_to={'data_kbn': 'CHN_CARGO'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='expenses.m_item', verbose_name='貨物概要区分')),
                ('china_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='中国側確認者')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='china_invoices', to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
            options={
                'verbose_name': '中国輸出Invoice',
                'verbose_name_plural': '中国輸出Invoice',
                'db_table': 't_china_invoice',
            },
        ),
        migrations.CreateModel(
            name='T_ChinaInvoiceMonthClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, unique=True, verbose_name='対象年月')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='締め日時')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='締め実行者')),
            ],
            options={
                'verbose_name': '中国輸出Invoice月締め',
                'verbose_name_plural': '中国輸出Invoice月締め',
                'db_table': 't_china_invoice_month_close',
            },
        ),
        migrations.CreateModel(
            name='T_ChinaInvoicePackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=expenses.models.china_invoice_packing_list_upload_path, verbose_name='Packing Listファイル')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='expenses.t_chinainvoice', verbose_name='Invoice')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
            ],
            options={
                'verbose_name': 'Packing List',
                'verbose_name_plural': 'Packing List',
                'db_table': 't_china_invoice_packing_list',
            },
        ),
    ]
