# Generated by Django 5.2.6 on 2026-08-21 09:58

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0123_china_invoice_master_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='invoice_file',
            field=models.FileField(blank=True, upload_to=expenses.models.china_invoice_upload_path, verbose_name='Invoiceファイル'),
        ),
    ]
