# Generated by Django 5.2.6 on 2026-08-22 16:50

import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0124_china_invoice_file_optional'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='gs_belong',
            table_comment='所属（グループ-ユーザー紐付け。GSESSIONのCMN_BELONGMより参照専用インポート）',
        ),
        migrations.AlterModelTableComment(
            name='gs_group',
            table_comment='組織・グループマスタ（GSESSIONのCMN_GROUPMより参照専用インポート）',
        ),
        migrations.AlterModelTableComment(
            name='gs_position',
            table_comment='役職マスタ（GSESSIONのCMN_POSITIONより参照専用インポート）',
        ),
        migrations.AlterModelTableComment(
            name='gs_ringi',
            table_comment='稟議データ本体（GSESSIONのRNG_RNDATAより参照専用インポート）',
        ),
        migrations.AlterModelTableComment(
            name='gs_usr',
            table_comment='ユーザー参照データ（GSESSIONのCMN_USRM+CMN_USRM_INFより参照専用インポート）',
        ),
        migrations.AlterModelTableComment(
            name='m_exchangefield',
            table_comment='見出し⇔フィールド変換マスタ（アップロード機能で汎用使用）',
        ),
        migrations.AlterModelTableComment(
            name='m_exchangerate',
            table_comment='換算為替レートマスタ',
        ),
        migrations.AlterModelTableComment(
            name='t_assetslowvalue',
            table_comment='少額資産台帳',
        ),
        migrations.AlterModelTableComment(
            name='t_assetssyncqueue',
            table_comment='固定資産同期キュー（Web編集→本物MDBへのPush待ち）',
        ),
        migrations.AlterModelTableComment(
            name='t_chinaexport',
            table_comment='中国輸出実績報告（経理投入の購入データを担当社員がフォロー）',
        ),
        migrations.AlterModelTableComment(
            name='t_chinainvoice',
            table_comment='中国輸出Invoice管理（Invoice単位の実績管理・経理と中国側の二重確認）',
        ),
        migrations.AlterModelTableComment(
            name='t_chinainvoicemonthclose',
            table_comment='中国輸出Invoice月締め',
        ),
        migrations.AlterModelTableComment(
            name='t_chinainvoicepackinglist',
            table_comment='中国輸出Invoice添付Packing List',
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_adate',
            field=models.DateTimeField(blank=True, db_comment='作成日時', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_auid',
            field=models.IntegerField(blank=True, db_comment='作成者旧USR_SID', null=True, verbose_name='作成者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_defgrp',
            field=models.IntegerField(blank=True, db_comment='デフォルトグループ区分', null=True, verbose_name='デフォルトグループ区分'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_edate',
            field=models.DateTimeField(blank=True, db_comment='更新日時', null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_euid',
            field=models.IntegerField(blank=True, db_comment='更新者旧USR_SID', null=True, verbose_name='更新者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='beg_grpkbn',
            field=models.IntegerField(blank=True, db_comment='グループ区分', null=True, verbose_name='グループ区分'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='grp_sid',
            field=models.IntegerField(blank=True, db_comment='旧グループSID', null=True, verbose_name='旧グループSID'),
        ),
        migrations.AlterField(
            model_name='gs_belong',
            name='usr_sid',
            field=models.IntegerField(blank=True, db_comment='旧ユーザーSID', null=True, verbose_name='旧ユーザーSID'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_adate',
            field=models.DateTimeField(blank=True, db_comment='作成日時', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_auid',
            field=models.IntegerField(blank=True, db_comment='作成者旧USR_SID', null=True, verbose_name='作成者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_comment',
            field=models.CharField(blank=True, db_comment='コメント', max_length=1000, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_edate',
            field=models.DateTimeField(blank=True, db_comment='更新日時', null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_euid',
            field=models.IntegerField(blank=True, db_comment='更新者旧USR_SID', null=True, verbose_name='更新者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_id',
            field=models.CharField(blank=True, db_comment='グループID', max_length=50, null=True, verbose_name='グループID'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_jkbn',
            field=models.IntegerField(blank=True, db_comment='状態区分', null=True, verbose_name='状態区分'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_name',
            field=models.CharField(blank=True, db_comment='グループ名', max_length=50, null=True, verbose_name='グループ名'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_name_kn',
            field=models.CharField(blank=True, db_comment='グループ名カナ', max_length=75, null=True, verbose_name='グループ名カナ'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_sid',
            field=models.IntegerField(db_comment='旧グループSID（PK）', primary_key=True, serialize=False, verbose_name='旧グループSID'),
        ),
        migrations.AlterField(
            model_name='gs_group',
            name='grp_sort',
            field=models.IntegerField(blank=True, db_comment='表示順', null=True, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_adate',
            field=models.DateTimeField(blank=True, db_comment='作成日時', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_auid',
            field=models.IntegerField(blank=True, db_comment='作成者旧USR_SID', null=True, verbose_name='作成者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_biko',
            field=models.CharField(blank=True, db_comment='備考', max_length=300, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_code',
            field=models.CharField(blank=True, db_comment='役職コード', max_length=15, null=True, verbose_name='役職コード'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_edate',
            field=models.DateTimeField(blank=True, db_comment='更新日時', null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_euid',
            field=models.IntegerField(blank=True, db_comment='更新者旧USR_SID', null=True, verbose_name='更新者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_name',
            field=models.CharField(blank=True, db_comment='役職名', max_length=30, null=True, verbose_name='役職名'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_sid',
            field=models.IntegerField(db_comment='旧役職SID（PK）', primary_key=True, serialize=False, verbose_name='旧役職SID'),
        ),
        migrations.AlterField(
            model_name='gs_position',
            name='pos_sort',
            field=models.IntegerField(blank=True, db_comment='表示順', null=True, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rct_ver',
            field=models.IntegerField(blank=True, db_comment='カテゴリバージョン', default=0, null=True, verbose_name='カテゴリバージョン'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_adate',
            field=models.DateTimeField(blank=True, db_comment='作成日時（監査）', null=True, verbose_name='作成日時(監査)'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_admcomment',
            field=models.CharField(blank=True, db_comment='管理者コメント', max_length=300, null=True, verbose_name='管理者コメント'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_appldate',
            field=models.DateTimeField(blank=True, db_comment='申請日時', null=True, verbose_name='申請日時'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_applicate',
            field=models.IntegerField(blank=True, db_comment='申請者旧USR_SID', null=True, verbose_name='申請者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_auid',
            field=models.IntegerField(blank=True, db_comment='作成者旧USR_SID', null=True, verbose_name='作成者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_compflg',
            field=models.IntegerField(blank=True, db_comment='完了フラグ', null=True, verbose_name='完了フラグ'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_edate',
            field=models.DateTimeField(blank=True, db_comment='更新日時（監査）', null=True, verbose_name='更新日時(監査)'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_euid',
            field=models.IntegerField(blank=True, db_comment='更新者旧USR_SID', null=True, verbose_name='更新者旧USR_SID'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_id',
            field=models.CharField(blank=True, db_comment='表示用ID', max_length=120, null=True, verbose_name='表示用ID'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_makedate',
            field=models.DateTimeField(blank=True, db_comment='作成日時', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_sid',
            field=models.IntegerField(db_comment='旧稟議SID（PK）', primary_key=True, serialize=False, verbose_name='旧稟議SID'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_status',
            field=models.IntegerField(blank=True, db_comment='ステータス', null=True, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rng_title',
            field=models.CharField(blank=True, db_comment='件名', max_length=100, null=True, verbose_name='件名'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rtp_sid',
            field=models.IntegerField(blank=True, db_comment='テンプレート旧SID', null=True, verbose_name='テンプレート旧SID'),
        ),
        migrations.AlterField(
            model_name='gs_ringi',
            name='rtp_ver',
            field=models.IntegerField(blank=True, db_comment='テンプレートバージョン', null=True, verbose_name='テンプレートバージョン'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='pos_sid',
            field=models.IntegerField(blank=True, db_comment='旧役職SID', null=True, verbose_name='旧役職SID'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usi_entrance_date',
            field=models.DateTimeField(blank=True, db_comment='入社日', null=True, verbose_name='入社日'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usi_mei',
            field=models.CharField(blank=True, db_comment='名', max_length=30, null=True, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usi_mei_kn',
            field=models.CharField(blank=True, db_comment='名カナ', max_length=60, null=True, verbose_name='名カナ'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usi_sei',
            field=models.CharField(blank=True, db_comment='姓', max_length=30, null=True, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usi_sei_kn',
            field=models.CharField(blank=True, db_comment='姓カナ', max_length=60, null=True, verbose_name='姓カナ'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usi_syain_no',
            field=models.CharField(blank=True, db_comment='社員番号', max_length=20, null=True, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usi_syozoku',
            field=models.CharField(blank=True, db_comment='所属名', max_length=60, null=True, verbose_name='所属名'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usi_yakusyoku',
            field=models.CharField(blank=True, db_comment='役職名', max_length=30, null=True, verbose_name='役職名'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usr_jkbn',
            field=models.IntegerField(blank=True, db_comment='在籍区分', null=True, verbose_name='在籍区分'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usr_lgid',
            field=models.CharField(blank=True, db_comment='ログインID', max_length=256, null=True, verbose_name='ログインID'),
        ),
        migrations.AlterField(
            model_name='gs_usr',
            name='usr_sid',
            field=models.IntegerField(db_comment='旧ユーザーSID（PK）', primary_key=True, serialize=False, verbose_name='旧ユーザーSID'),
        ),
        migrations.AlterField(
            model_name='m_exchangefield',
            name='table_name',
            field=models.CharField(db_comment='アップロード先テーブル名', max_length=100, verbose_name='アップロード先テーブル'),
        ),
        migrations.AlterField(
            model_name='m_exchangefield',
            name='up_field_name',
            field=models.CharField(db_comment='書き出し先フィールド名', max_length=100, verbose_name='書き出し先フィールド名'),
        ),
        migrations.AlterField(
            model_name='m_exchangefield',
            name='updata_title',
            field=models.CharField(db_comment='読み込みファイルの見出し名', max_length=100, verbose_name='読み込みファイルの見出し名'),
        ),
        migrations.AlterField(
            model_name='m_exchangerate',
            name='exchange_rate',
            field=models.DecimalField(db_comment='換算レート', decimal_places=2, max_digits=5, verbose_name='換算レート'),
        ),
        migrations.AlterField(
            model_name='m_exchangerate',
            name='keijo_ym',
            field=models.CharField(db_comment='計上年月（YYYYMM）', max_length=6, verbose_name='計上年月'),
        ),
        migrations.AlterField(
            model_name='m_exchangerate',
            name='tsuka_cd',
            field=models.CharField(db_comment='通貨コード', max_length=3, verbose_name='通貨コード'),
        ),
        migrations.AlterField(
            model_name='m_item',
            name='data_kbn',
            field=models.CharField(blank=True, db_comment='データ区分（CUR=通貨/PAY=精算方法/TRA=日当単価/MST=マスタ設定メニュー等）', max_length=10, verbose_name='データ区分'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='acquisition_date',
            field=models.DateTimeField(blank=True, db_comment='取得年月日', null=True, verbose_name='年月日'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='acquisition_price',
            field=models.DecimalField(blank=True, db_comment='取得価格', decimal_places=4, max_digits=18, null=True, verbose_name='取得価格'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='bumon_cd',
            field=models.CharField(blank=True, db_comment='部門コード', max_length=10, null=True, verbose_name='部門コード'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='bumon_name',
            field=models.CharField(blank=True, db_comment='部門名', max_length=50, null=True, verbose_name='部門名'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='cre_date',
            field=models.DateTimeField(auto_now_add=True, db_comment='作成日時', verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='item_name',
            field=models.CharField(blank=True, db_comment='品名', max_length=100, null=True, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='location_cd',
            field=models.CharField(blank=True, db_comment='設置場所コード', max_length=10, null=True, verbose_name='設置場所コード'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='location_name',
            field=models.CharField(blank=True, db_comment='設置場所名', max_length=50, null=True, verbose_name='設置場所名'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='low_value_asset_no',
            field=models.CharField(db_comment='小額資産番号（PK）', max_length=13, primary_key=True, serialize=False, verbose_name='小額資産番号'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='maker_name',
            field=models.CharField(blank=True, db_comment='メーカー名', max_length=50, null=True, verbose_name='メーカー名'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='model_no',
            field=models.CharField(blank=True, db_comment='品番', max_length=50, null=True, verbose_name='品番'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='purpose',
            field=models.CharField(blank=True, db_comment='用途', max_length=100, null=True, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='serial_no',
            field=models.CharField(blank=True, db_comment='製造番号', max_length=50, null=True, verbose_name='製造番号'),
        ),
        migrations.AlterField(
            model_name='t_assetslowvalue',
            name='up_date',
            field=models.DateTimeField(auto_now=True, db_comment='更新日時', verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='t_assetssyncqueue',
            name='asset_no',
            field=models.CharField(db_comment='資産NO', max_length=13, verbose_name='資産NO'),
        ),
        migrations.AlterField(
            model_name='t_assetssyncqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='登録日時', verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='t_assetssyncqueue',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', db_comment='登録者社員番号（FK: m_user.man_number）', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='man_number', verbose_name='登録者'),
        ),
        migrations.AlterField(
            model_name='t_assetssyncqueue',
            name='error_msg',
            field=models.CharField(blank=True, db_comment='エラー内容', default='', max_length=500, verbose_name='エラー内容'),
        ),
        migrations.AlterField(
            model_name='t_assetssyncqueue',
            name='operation',
            field=models.CharField(choices=[('insert', '新規登録'), ('update', '更新')], db_comment='操作（insert=新規登録/update=更新）', max_length=10, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='t_assetssyncqueue',
            name='payload',
            field=models.JSONField(db_comment='変更内容（変更フィールドのみのJSON）', verbose_name='変更内容'),
        ),
        migrations.AlterField(
            model_name='t_assetssyncqueue',
            name='processed_at',
            field=models.DateTimeField(blank=True, db_comment='処理日時', null=True, verbose_name='処理日時'),
        ),
        migrations.AlterField(
            model_name='t_assetssyncqueue',
            name='queue_id',
            field=models.AutoField(db_comment='キューID（PK）', primary_key=True, serialize=False, verbose_name='キューID'),
        ),
        migrations.AlterField(
            model_name='t_assetssyncqueue',
            name='status',
            field=models.CharField(choices=[('pending', '未送信'), ('done', '送信済'), ('error', 'エラー')], db_comment='状態（pending=未送信/done=送信済/error=エラー）', default='pending', max_length=10, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='account_cd',
            field=models.CharField(blank=True, db_comment='勘定科目コード', max_length=10, null=True, verbose_name='科目コード'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='account_name',
            field=models.CharField(blank=True, db_comment='勘定科目名', max_length=30, null=True, verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='amount',
            field=models.DecimalField(db_comment='金額', decimal_places=2, max_digits=10, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='burden_bumon_cd',
            field=models.CharField(blank=True, db_comment='負担部門コード', max_length=10, null=True, verbose_name='負担部門コード'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='burden_bumon_name',
            field=models.CharField(blank=True, db_comment='負担部署名', max_length=20, null=True, verbose_name='負担部署名'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='export_date',
            field=models.DateField(blank=True, db_comment='輸出日', null=True, verbose_name='輸出日'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='export_planned_date',
            field=models.DateField(blank=True, db_comment='輸出予定日', null=True, verbose_name='輸出予定日'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='invoice_no',
            field=models.CharField(blank=True, db_comment='インボイスNo', max_length=30, null=True, verbose_name='インボイスNo'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='item_name1',
            field=models.CharField(db_comment='品目名1', max_length=50, verbose_name='品目名1'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='item_name2',
            field=models.CharField(blank=True, db_comment='品目名2', max_length=50, null=True, verbose_name='品目名2'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='order_bumon_name',
            field=models.CharField(blank=True, db_comment='発注部署名', max_length=20, null=True, verbose_name='発注部署名'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='order_no',
            field=models.CharField(blank=True, db_comment='注文番号', max_length=15, null=True, verbose_name='注文番号'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='order_staff_name',
            field=models.CharField(blank=True, db_comment='発注担当名', max_length=20, null=True, verbose_name='発注担当名'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='purchase_date',
            field=models.DateField(blank=True, db_comment='購入日', null=True, verbose_name='購入日'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='quantity',
            field=models.DecimalField(blank=True, db_comment='数量', decimal_places=2, max_digits=10, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='supplier_cd',
            field=models.CharField(blank=True, db_comment='仕入先コード', max_length=10, null=True, verbose_name='仕入先コード'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='supplier_name',
            field=models.CharField(blank=True, db_comment='仕入先名', max_length=30, null=True, verbose_name='仕入先名'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='unit_price',
            field=models.DecimalField(blank=True, db_comment='仕入単価', decimal_places=2, max_digits=15, null=True, verbose_name='仕入単価'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='最終更新日時', verbose_name='最終更新日時'),
        ),
        migrations.AlterField(
            model_name='t_chinaexport',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='最終更新者ユーザーID（FK: m_user）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='accounting_confirmed',
            field=models.BooleanField(db_comment='経理確認フラグ', default=False, verbose_name='経理確認'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='accounting_confirmed_at',
            field=models.DateTimeField(blank=True, db_comment='経理確認日時', null=True, verbose_name='経理確認日時'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='accounting_confirmed_by',
            field=models.ForeignKey(blank=True, db_comment='経理確認者ユーザーID（FK: m_user）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='経理確認者'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='adjustment_rate_value',
            field=models.DecimalField(db_comment='加算調整率', decimal_places=2, max_digits=5, verbose_name='加算調整率'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='cargo_category',
            field=models.ForeignKey(db_comment='貨物概要区分ID（FK: m_item data_kbn=CHN_CARGO）', limit_choices_to={'data_kbn': 'CHN_CARGO'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='expenses.m_item', verbose_name='貨物概要区分'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='cargo_note',
            field=models.CharField(blank=True, db_comment='貨物概要補足', max_length=200, verbose_name='貨物概要補足'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='china_confirm_status',
            field=models.CharField(choices=[('unconfirmed', '未確認'), ('confirmed', '確認済み'), ('difference', '差異あり')], db_comment='中国側確認（unconfirmed=未確認/confirmed=確認済み/difference=差異あり）', default='unconfirmed', max_length=20, verbose_name='中国側確認'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='china_confirmed_at',
            field=models.DateTimeField(blank=True, db_comment='中国側確認日時', null=True, verbose_name='中国側確認日時'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='china_confirmed_by',
            field=models.ForeignKey(blank=True, db_comment='中国側確認者ユーザーID（FK: m_user）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='中国側確認者'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='export_date',
            field=models.DateField(db_comment='輸出日', verbose_name='輸出日'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='invoice_file',
            field=models.FileField(blank=True, db_comment='Invoiceファイルパス', upload_to=expenses.models.china_invoice_upload_path, verbose_name='Invoiceファイル'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='invoice_no',
            field=models.CharField(db_comment='Invoice No', max_length=50, verbose_name='Invoice No'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='invoice_total',
            field=models.DecimalField(db_comment='Invoice合計金額', decimal_places=2, max_digits=15, verbose_name='Invoice Total'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='management_no',
            field=models.CharField(blank=True, db_comment='管理番号（EX-YYYYMMDD-NNN形式で自動採番）', max_length=20, unique=True, verbose_name='管理番号'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='登録日時', verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoice',
            name='reporter',
            field=models.ForeignKey(db_comment='報告者ユーザーID（FK: m_user）', on_delete=django.db.models.deletion.PROTECT, related_name='china_invoices', to=settings.AUTH_USER_MODEL, verbose_name='報告者'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoicemonthclose',
            name='closed_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='締め日時', verbose_name='締め日時'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoicemonthclose',
            name='closed_by',
            field=models.ForeignKey(db_comment='締め実行者ユーザーID（FK: m_user）', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='締め実行者'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoicemonthclose',
            name='year_month',
            field=models.CharField(db_comment='対象年月（YYYY-MM）', max_length=7, unique=True, verbose_name='対象年月'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoicepackinglist',
            name='file',
            field=models.FileField(db_comment='Packing Listファイルパス', upload_to=expenses.models.china_invoice_packing_list_upload_path, verbose_name='Packing Listファイル'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoicepackinglist',
            name='invoice',
            field=models.ForeignKey(db_comment='InvoiceID（FK: t_china_invoice）', on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='expenses.t_chinainvoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoicepackinglist',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='登録日時', verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='t_chinainvoicepackinglist',
            name='uploaded_by',
            field=models.ForeignKey(db_comment='登録者ユーザーID（FK: m_user）', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
    ]
