# Generated by Django 5.2.6 on 2026-09-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0126_add_mysql_comments_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_user',
            name='lunch_site_cd',
            field=models.IntegerField(blank=True, db_comment='お弁当受取拠点（m_item data_kbn=LUNCH の key）', null=True, verbose_name='お弁当受取拠点'),
        ),
    ]
